server:
  port: 8081
  servlet:
    encoding:
      charset: UTF-8
      force: true

spring:
  application:
    name: mcp-client
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 11MB
  ai:
    chat:
      client:
        enabled: true
    openai:
      api-key: ${OPENAI_API_KEY}
      base-url: https://api.openai.com
      chat:
        options:
          max-tokens: 1024
          temperature: 0.7
          top-p: 1.0
          model: gpt-3.5-turbo
    deepseek:
      api-key: ${DEEPSEEK_API_KEY}
      base-url: https://api.deepseek.com
      chat:
        options:
          max-tokens: 1024
          temperature: 0.7
          model: deepseek-chat
    vectorstore:
      redis:
        index-name: sb3md-v
        prefix: "vtr:"
    embedding:
      transformer:
        cache:
          enabled: true
          directory: .env/transformer-cache
  data:
    redis:
      host: 127.0.0.1
      port: 8379
      password: your-pwd

logging:
  level:
    root: INFO
    cn.netbuffer: DEBUG
  charset:
    console: UTF-8
    file: UTF-8