server:
  port: 8081
  servlet:
    encoding:
      charset: UTF-8
      force: true

spring:
  application:
    name: mcp-client
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 11MB
  ai:
    chat:
      client:
        enabled: true
    openai:
      api-key: ${OPENAI_API_KEY}
      base-url: https://api.openai.com
      chat:
        options:
          max-tokens: 1024
          temperature: 0.7
          top-p: 1.0
          model: gpt-3.5-turbo
    deepseek:
      api-key: ${DEEPSEEK_API_KEY}
      base-url: https://api.deepseek.com
      chat:
        options:
          max-tokens: 1024
          temperature: 0.7
          model: deepseek-chat
    vectorstore:
      redis:
        index-name: sb3md-v
        prefix: "vtr:"
    embedding:
      transformer:
        cache:
          enabled: true
          directory: .env/transformer-cache
    mcp:
      client:
        enabled: true
        request-timeout: 30s
        type: ASYNC
        stdio:
          servers-configuration: classpath:mcp-servers.json
        streamable-http:
          connections:
            baidu-map-server:
              url: https://mcp.map.baidu.com
              endpoint: ${BAIDU_MAP_API_KEY}
  data:
    redis:
      host: 127.0.0.1
      port: 8379
      password: your-pwd

logging:
  level:
    root: INFO
    cn.netbuffer: DEBUG
    org:
      springframework:
        ai: DEBUG
  charset:
    console: UTF-8
    file: UTF-8

forest:
  backend: okhttp3             # 后端HTTP框架（默认为 okhttp3）
  max-connections: 100        # 连接池最大连接数（默认为 500）
  max-route-connections: 50   # 每个路由的最大连接数（默认为 500）
  max-request-queue-size: 100  # [自v1.5.22版本起可用] 最大请求等待队列大小
  max-async-thread-size: 10   # [自v1.5.21版本起可用] 最大异步线程数
  max-async-queue-size: 10     # [自v1.5.22版本起可用] 最大异步线程池队列大小
  timeout: 3000                # [已不推荐使用] 请求超时时间，单位为毫秒（默认为 3000）
  connect-timeout: 3000        # 连接超时时间，单位为毫秒（默认为 timeout）
  read-timeout: 10000           # 数据读取超时时间，单位为毫秒（默认为 timeout）
  max-retry-count: 0           # 请求失败后重试次数（默认为 0 次不重试）
  ssl-protocol: TLS            # 单向验证的HTTPS的默认TLS协议（默认为 TLS）
  log-enabled: true            # 打开或关闭日志（默认为 true）
  log-request: true            # 打开/关闭Forest请求日志（默认为 true）
  log-response-status: true    # 打开/关闭Forest响应状态日志（默认为 true）
  log-response-content: true   # 打开/关闭Forest响应内容日志（默认为 false）
  async-mode: platform         # [自v1.5.27版本起可用] 异步模式（默认为 platform）
  variables:
    searxng:
      url: http://127.0.0.1:8381
