server:
  port: 8082
  servlet:
    encoding:
      charset: UTF-8
      force: true

spring:
  application:
    name: mcp-server1
  ai:
    mcp:
      server:
        enabled: true
        name: mcp-server1
        version: 1.0.0
        type: async
        protocol: sse
        sse-endpoint: /sse

logging:
  level:
    root: INFO
    cn.netbuffer: DEBUG
    org:
      springframework:
        ai: DEBUG
  charset:
    console: UTF-8
    file: UTF-8

forest:
  backend: okhttp3
  max-connections: 100
  max-route-connections: 50
  max-request-queue-size: 100
  max-async-thread-size: 10
  max-async-queue-size: 10
  timeout: 3000
  connect-timeout: 3000
  read-timeout: 10000
  max-retry-count: 0
  ssl-protocol: TLS
  log-enabled: true
  log-request: true
  log-response-status: true
  log-response-content: true
  async-mode: platform
